# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170622_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
