# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_confirmedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorder',
            name='email',
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
