# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='products/product_images/uploads'),
        ),
    ]
